"%ProgramFiles(x86)%\\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe" linq2db.PerformanceTest.sln /p:Configuration=Release  /t:Restore;Rebuild /v:m

dotnet "ConsoleRunner\bin\Release\netcoreapp2.1\ConsoleRunner.dll"
"ConsoleRunner\bin\Release\ConsoleRunner.exe"
dotnet "ConsoleRunner\bin\Release\netcoreapp2.1\ConsoleRunner.dll"
"ConsoleRunner\bin\Release\ConsoleRunner.exe"
dotnet "ConsoleRunner\bin\Release\netcoreapp2.1\ConsoleRunner.dll"
"ConsoleRunner\bin\Release\ConsoleRunner.exe"
dotnet "ConsoleRunner\bin\Release\netcoreapp2.1\ConsoleRunner.dll"
"ConsoleRunner\bin\Release\ConsoleRunner.exe"
dotnet "ConsoleRunner\bin\Release\netcoreapp2.1\ConsoleRunner.dll"
"ConsoleRunner\bin\Release\ConsoleRunner.exe"
dotnet "ConsoleRunner\bin\Release\netcoreapp2.1\ConsoleRunner.dll"
"ConsoleRunner\bin\Release\ConsoleRunner.exe"
dotnet "ConsoleRunner\bin\Release\netcoreapp2.1\ConsoleRunner.dll"
"ConsoleRunner\bin\Release\ConsoleRunner.exe"
dotnet "ConsoleRunner\bin\Release\netcoreapp2.1\ConsoleRunner.dll"
"ConsoleRunner\bin\Release\ConsoleRunner.exe"
dotnet "ConsoleRunner\bin\Release\netcoreapp2.1\ConsoleRunner.dll"
"ConsoleRunner\bin\Release\ConsoleRunner.exe"
dotnet "ConsoleRunner\bin\Release\netcoreapp2.1\ConsoleRunner.dll"
"ConsoleRunner\bin\Release\ConsoleRunner.exe"
