//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1573, 1591

using System;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;

namespace PerformanceTest.Views.TestControl
{
	public partial class MethodViewModel : INotifyPropertyChanged
	{
		#region Name : string

		private string _name;
		public  string  Name
		{
			get { return _name; }
			set
			{
				if (_name != value)
				{
					BeforeNameChanged(value);
					_name = value;
					AfterNameChanged();

					OnDisplayNameChanged();
				}
			}
		}

		#region INotifyPropertyChanged support

		partial void BeforeNameChanged(string newValue);
		partial void AfterNameChanged ();

		public const string NameOfName = "Name";

		private static readonly PropertyChangedEventArgs _nameChangedEventArgs = new PropertyChangedEventArgs(NameOfName);

		private void OnNameChanged()
		{
			OnPropertyChanged(_nameChangedEventArgs);
		}

		#endregion

		#endregion

		#region Repeat : long

		private long _repeat;
		public  long  Repeat
		{
			get { return _repeat; }
			set
			{
				if (_repeat != value)
				{
					BeforeRepeatChanged(value);
					_repeat = value;
					AfterRepeatChanged();

					OnDisplayNameChanged();
				}
			}
		}

		#region INotifyPropertyChanged support

		partial void BeforeRepeatChanged(long newValue);
		partial void AfterRepeatChanged ();

		public const string NameOfRepeat = "Repeat";

		private static readonly PropertyChangedEventArgs _repeatChangedEventArgs = new PropertyChangedEventArgs(NameOfRepeat);

		private void OnRepeatChanged()
		{
			OnPropertyChanged(_repeatChangedEventArgs);
		}

		#endregion

		#endregion

		#region Take : long?

		private long? _take;
		public  long?  Take
		{
			get { return _take; }
			set
			{
				if (_take != value)
				{
					BeforeTakeChanged(value);
					_take = value;
					AfterTakeChanged();

					OnDisplayNameChanged();
				}
			}
		}

		#region INotifyPropertyChanged support

		partial void BeforeTakeChanged(long? newValue);
		partial void AfterTakeChanged ();

		public const string NameOfTake = "Take";

		private static readonly PropertyChangedEventArgs _takeChangedEventArgs = new PropertyChangedEventArgs(NameOfTake);

		private void OnTakeChanged()
		{
			OnPropertyChanged(_takeChangedEventArgs);
		}

		#endregion

		#endregion

		#region DisplayName : string

		public string DisplayName
		{
			get { return Name + " / " + Repeat + (Take.HasValue ? " / " + Take : ""); }
		}

		#region INotifyPropertyChanged support

		public const string NameOfDisplayName = "DisplayName";

		private static readonly PropertyChangedEventArgs _displayNameChangedEventArgs = new PropertyChangedEventArgs(NameOfDisplayName);

		private void OnDisplayNameChanged()
		{
			OnPropertyChanged(_displayNameChangedEventArgs);
		}

		#endregion

		#endregion

		#region Times : ObservableCollection<TimeViewModel>

		private ObservableCollection<TimeViewModel> _times;
		public  ObservableCollection<TimeViewModel>  Times
		{
			get { return _times; }
			set
			{
				if (_times != value)
				{
					BeforeTimesChanged(value);
					_times = value;
					AfterTimesChanged();

					OnTimesChanged();
				}
			}
		}

		#region INotifyPropertyChanged support

		partial void BeforeTimesChanged(ObservableCollection<TimeViewModel> newValue);
		partial void AfterTimesChanged ();

		public const string NameOfTimes = "Times";

		private static readonly PropertyChangedEventArgs _timesChangedEventArgs = new PropertyChangedEventArgs(NameOfTimes);

		private void OnTimesChanged()
		{
			OnPropertyChanged(_timesChangedEventArgs);
		}

		#endregion

		#endregion

		#region INotifyPropertyChanged support

		[field : NonSerialized]
		public virtual event PropertyChangedEventHandler PropertyChanged;

		protected void OnPropertyChanged(string propertyName)
		{
			var propertyChanged = PropertyChanged;

			if (propertyChanged != null)
			{
				propertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		protected void OnPropertyChanged(PropertyChangedEventArgs arg)
		{
			var propertyChanged = PropertyChanged;

			if (propertyChanged != null)
			{
				propertyChanged(this, arg);
			}
		}

		#endregion
	}

	public partial class ProviderViewModel : INotifyPropertyChanged
	{
		#region Name : string

		private string _name;
		public  string  Name
		{
			get { return _name; }
			set
			{
				if (_name != value)
				{
					BeforeNameChanged(value);
					_name = value;
					AfterNameChanged();

					OnNameChanged();
				}
			}
		}

		#region INotifyPropertyChanged support

		partial void BeforeNameChanged(string newValue);
		partial void AfterNameChanged ();

		public const string NameOfName = "Name";

		private static readonly PropertyChangedEventArgs _nameChangedEventArgs = new PropertyChangedEventArgs(NameOfName);

		private void OnNameChanged()
		{
			OnPropertyChanged(_nameChangedEventArgs);
		}

		#endregion

		#endregion

		#region Color : Brush

		private Brush _color;
		public  Brush  Color
		{
			get { return _color; }
			set
			{
				if (_color != value)
				{
					BeforeColorChanged(value);
					_color = value;
					AfterColorChanged();

					OnColorChanged();
				}
			}
		}

		#region INotifyPropertyChanged support

		partial void BeforeColorChanged(Brush newValue);
		partial void AfterColorChanged ();

		public const string NameOfColor = "Color";

		private static readonly PropertyChangedEventArgs _colorChangedEventArgs = new PropertyChangedEventArgs(NameOfColor);

		private void OnColorChanged()
		{
			OnPropertyChanged(_colorChangedEventArgs);
		}

		#endregion

		#endregion

		#region INotifyPropertyChanged support

		[field : NonSerialized]
		public virtual event PropertyChangedEventHandler PropertyChanged;

		protected void OnPropertyChanged(string propertyName)
		{
			var propertyChanged = PropertyChanged;

			if (propertyChanged != null)
			{
				propertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		protected void OnPropertyChanged(PropertyChangedEventArgs arg)
		{
			var propertyChanged = PropertyChanged;

			if (propertyChanged != null)
			{
				propertyChanged(this, arg);
			}
		}

		#endregion
	}

	public partial class TestViewModel : INotifyPropertyChanged
	{
		#region Platform : string

		private string _platform;
		public  string  Platform
		{
			get { return _platform; }
			set
			{
				if (_platform != value)
				{
					BeforePlatformChanged(value);
					_platform = value;
					AfterPlatformChanged();

					OnPlatformChanged();
				}
			}
		}

		#region INotifyPropertyChanged support

		partial void BeforePlatformChanged(string newValue);
		partial void AfterPlatformChanged ();

		public const string NameOfPlatform = "Platform";

		private static readonly PropertyChangedEventArgs _platformChangedEventArgs = new PropertyChangedEventArgs(NameOfPlatform);

		private void OnPlatformChanged()
		{
			OnPropertyChanged(_platformChangedEventArgs);
		}

		#endregion

		#endregion

		#region Name : string

		private string _name;
		public  string  Name
		{
			get { return _name; }
			set
			{
				if (_name != value)
				{
					BeforeNameChanged(value);
					_name = value;
					AfterNameChanged();

					OnNameChanged();
				}
			}
		}

		#region INotifyPropertyChanged support

		partial void BeforeNameChanged(string newValue);
		partial void AfterNameChanged ();

		public const string NameOfName = "Name";

		private static readonly PropertyChangedEventArgs _nameChangedEventArgs = new PropertyChangedEventArgs(NameOfName);

		private void OnNameChanged()
		{
			OnPropertyChanged(_nameChangedEventArgs);
		}

		#endregion

		#endregion

		#region Methods : ObservableCollection<MethodViewModel>

		private ObservableCollection<MethodViewModel> _methods;
		public  ObservableCollection<MethodViewModel>  Methods
		{
			get { return _methods; }
			set
			{
				if (_methods != value)
				{
					BeforeMethodsChanged(value);
					_methods = value;
					AfterMethodsChanged();

					OnMethodsChanged();
				}
			}
		}

		#region INotifyPropertyChanged support

		partial void BeforeMethodsChanged(ObservableCollection<MethodViewModel> newValue);
		partial void AfterMethodsChanged ();

		public const string NameOfMethods = "Methods";

		private static readonly PropertyChangedEventArgs _methodsChangedEventArgs = new PropertyChangedEventArgs(NameOfMethods);

		private void OnMethodsChanged()
		{
			OnPropertyChanged(_methodsChangedEventArgs);
		}

		#endregion

		#endregion

		#region Providers : ObservableCollection<ProviderViewModel>

		private ObservableCollection<ProviderViewModel> _providers;
		public  ObservableCollection<ProviderViewModel>  Providers
		{
			get { return _providers; }
			set
			{
				if (_providers != value)
				{
					BeforeProvidersChanged(value);
					_providers = value;
					AfterProvidersChanged();

					OnProvidersChanged();
				}
			}
		}

		#region INotifyPropertyChanged support

		partial void BeforeProvidersChanged(ObservableCollection<ProviderViewModel> newValue);
		partial void AfterProvidersChanged ();

		public const string NameOfProviders = "Providers";

		private static readonly PropertyChangedEventArgs _providersChangedEventArgs = new PropertyChangedEventArgs(NameOfProviders);

		private void OnProvidersChanged()
		{
			OnPropertyChanged(_providersChangedEventArgs);
		}

		#endregion

		#endregion

		#region INotifyPropertyChanged support

		[field : NonSerialized]
		public virtual event PropertyChangedEventHandler PropertyChanged;

		protected void OnPropertyChanged(string propertyName)
		{
			var propertyChanged = PropertyChanged;

			if (propertyChanged != null)
			{
				propertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		protected void OnPropertyChanged(PropertyChangedEventArgs arg)
		{
			var propertyChanged = PropertyChanged;

			if (propertyChanged != null)
			{
				propertyChanged(this, arg);
			}
		}

		#endregion
	}

	public partial class TimeViewModel : INotifyPropertyChanged
	{
		#region Name : string

		private string _name;
		public  string  Name
		{
			get { return _name; }
			set
			{
				if (_name != value)
				{
					BeforeNameChanged(value);
					_name = value;
					AfterNameChanged();

					OnNameChanged();
				}
			}
		}

		#region INotifyPropertyChanged support

		partial void BeforeNameChanged(string newValue);
		partial void AfterNameChanged ();

		public const string NameOfName = "Name";

		private static readonly PropertyChangedEventArgs _nameChangedEventArgs = new PropertyChangedEventArgs(NameOfName);

		private void OnNameChanged()
		{
			OnPropertyChanged(_nameChangedEventArgs);
		}

		#endregion

		#endregion

		#region Time : TimeSpan

		private TimeSpan _time;
		public  TimeSpan  Time
		{
			get { return _time; }
			set
			{
				if (_time != value)
				{
					BeforeTimeChanged(value);
					_time = value;
					AfterTimeChanged();

					OnWidthChanged();
				}
			}
		}

		#region INotifyPropertyChanged support

		partial void BeforeTimeChanged(TimeSpan newValue);
		partial void AfterTimeChanged ();

		public const string NameOfTime = "Time";

		private static readonly PropertyChangedEventArgs _timeChangedEventArgs = new PropertyChangedEventArgs(NameOfTime);

		private void OnTimeChanged()
		{
			OnPropertyChanged(_timeChangedEventArgs);
		}

		#endregion

		#endregion

		#region MaxTime : TimeSpan

		private TimeSpan _maxTime;
		public  TimeSpan  MaxTime
		{
			get { return _maxTime; }
			set
			{
				if (_maxTime != value)
				{
					BeforeMaxTimeChanged(value);
					_maxTime = value;
					AfterMaxTimeChanged();

					OnWidthChanged();
				}
			}
		}

		#region INotifyPropertyChanged support

		partial void BeforeMaxTimeChanged(TimeSpan newValue);
		partial void AfterMaxTimeChanged ();

		public const string NameOfMaxTime = "MaxTime";

		private static readonly PropertyChangedEventArgs _maxTimeChangedEventArgs = new PropertyChangedEventArgs(NameOfMaxTime);

		private void OnMaxTimeChanged()
		{
			OnPropertyChanged(_maxTimeChangedEventArgs);
		}

		#endregion

		#endregion

		#region Border : Border

		private Border _border;
		public  Border  Border
		{
			get { return _border; }
			set
			{
				if (_border != value)
				{
					BeforeBorderChanged(value);
					_border = value;
					AfterBorderChanged();

					OnBorderChanged();
				}
			}
		}

		#region INotifyPropertyChanged support

		partial void BeforeBorderChanged(Border newValue);
		partial void AfterBorderChanged ();

		public const string NameOfBorder = "Border";

		private static readonly PropertyChangedEventArgs _borderChangedEventArgs = new PropertyChangedEventArgs(NameOfBorder);

		private void OnBorderChanged()
		{
			OnPropertyChanged(_borderChangedEventArgs);
		}

		#endregion

		#endregion

		#region Width : int

		private int _width;
		public  int  Width
		{
			get { return _width; }
			set
			{
				if (_width != value)
				{
					BeforeWidthChanged(value);
					_width = value;
					AfterWidthChanged();

					OnWidthChanged();
				}
			}
		}

		#region INotifyPropertyChanged support

		partial void BeforeWidthChanged(int newValue);
		partial void AfterWidthChanged ();

		public const string NameOfWidth = "Width";

		private static readonly PropertyChangedEventArgs _widthChangedEventArgs = new PropertyChangedEventArgs(NameOfWidth);

		private void OnWidthChanged()
		{
			OnPropertyChanged(_widthChangedEventArgs);
		}

		#endregion

		#endregion

		#region Color : Brush

		private Brush _color;
		public  Brush  Color
		{
			get { return _color; }
			set
			{
				if (_color != value)
				{
					BeforeColorChanged(value);
					_color = value;
					AfterColorChanged();

					OnColorChanged();
				}
			}
		}

		#region INotifyPropertyChanged support

		partial void BeforeColorChanged(Brush newValue);
		partial void AfterColorChanged ();

		public const string NameOfColor = "Color";

		private static readonly PropertyChangedEventArgs _colorChangedEventArgs = new PropertyChangedEventArgs(NameOfColor);

		private void OnColorChanged()
		{
			OnPropertyChanged(_colorChangedEventArgs);
		}

		#endregion

		#endregion

		#region Count : int

		public int Count
		{
			get { return Watches.Length; }
		}

		#region INotifyPropertyChanged support

		public const string NameOfCount = "Count";

		private static readonly PropertyChangedEventArgs _countChangedEventArgs = new PropertyChangedEventArgs(NameOfCount);

		private void OnCountChanged()
		{
			OnPropertyChanged(_countChangedEventArgs);
		}

		#endregion

		#endregion

		#region INotifyPropertyChanged support

		[field : NonSerialized]
		public virtual event PropertyChangedEventHandler PropertyChanged;

		protected void OnPropertyChanged(string propertyName)
		{
			var propertyChanged = PropertyChanged;

			if (propertyChanged != null)
			{
				propertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		protected void OnPropertyChanged(PropertyChangedEventArgs arg)
		{
			var propertyChanged = PropertyChanged;

			if (propertyChanged != null)
			{
				propertyChanged(this, arg);
			}
		}

		#endregion
	}
}
